### ISSUE TITLE
Task management

### ISSUE THREAD

**Issue by dhurimkelmendi** [dhurimkelmendi/sdmd-practical3#1]
This is where we will separate the tasks, so that we work as a team, and avoid the problems we had during the last practical. The tasks can be seen in TODO.xml

**Comment by vsemertzidis** [comment]
I would like to choose those:

(1) Add an app bar to all the screens with proper navigation support
    (2) (back arrow) and move the actions there (create meal, upvote meal)
    (3) Use the app bar title to properly convey to the user where in the app they are-->
(4) Support tablets by creating a special landscape tablet master / detail view-->
    (5) Write three (3) integration tests for the app-->

(You can check the other that left, and if you want we can discuss if you like to share any of the rest of them so we can share the workload evenly 👍  💃

**Comment by dhurimkelmendi** [comment]
@vsemertzidis ok, I'll choose 
    

    

    

    

please finish the chosen tasks ASAP, so that we continue working on the other tasks :tada:

**Comment by dhurimkelmendi** [comment]
@vsemertzidis  and remember, the first TODO also includes:
TODO(1) Use the app bar title to properly convey to the user where in the app they are
