### ISSUE TITLE
upvote URL not working

### ISSUE THREAD

**Issue by dhurimkelmendi** [dhurimkelmendi/sdmd-practical3#3]
Hello @trumpets ! 
I was trying to upvote a meal with the URL below:
http://clubs-sdmdcity.rhcloud.com/rest/types/1/meals/2/upvote

and this was the response:
![selection_001](https://cloud.githubusercontent.com/assets/10913677/25828260/f2f529ce-3457-11e7-88b6-b00e2a8ec889.png)

Is the URL above wrong?

**Comment by trumpets** [comment]
Read the error Dhurim. What does it say?

**Comment by trumpets** [comment]
Also read endpoint description in the practical handout :)

**Comment by dhurimkelmendi** [comment]
in the handout, the URL for the upvote action is:
http://clubs-sdmdcity.rhcloud.com/rest/types/MEAL_TYPE_ID/meals/MEAL_ID/upvote

And the URL I took as an example here is:
http://clubs-sdmdcity.rhcloud.com/rest/types/1/meals/2/upvote

But it shows HTTP Status 405. Can't figure out why :cry:

**Comment by trumpets** [comment]
What does http 405 mean? What else does the handout say? Read carefully!

**Comment by trumpets** [comment]
All https statuses mean something and we always use them appropriately when
building apis

**Comment by trumpets** [comment]
@DhurimKelmendi did you manage to figure out what was the problem?

**Comment by dhurimkelmendi** [comment]
@trumpets yes, I was doing a GET request on a URL where only POST is supported! :smile:

**Comment by trumpets** [comment]
@DhurimKelmendi there you go :)

Always pay attention to the fine print :) and if the API is designed properly, those HTTP error codes can give you a lot of information on what is wrong :)
