### ISSUE TITLE
Meal Creation Local Duplicate

### ISSUE THREAD

**Issue by dhurimkelmendi** [dhurimkelmendi/sdmd-practical3#4]
Hello @trumpets !
Not sure if this has to do with the changes in the API, but when I create a meal, the app has two duplicate records, one of which, when clicked causes the app to crash. I discussed with some of the colleagues and they had the same issue. I have not changed anything in the meal creation and it was initially working great, but I guess it has to do with the changes in the API.
Here are the meals and Omelette is the meal which was created from this device:
![selection_002](https://cloud.githubusercontent.com/assets/10913677/25872407/3fca4002-3513-11e7-83a2-1eb35c02f1d5.png)

When I click on the first Omelette, it raises a NullPointerException. The second Omelette record works fine.

Thank you for your help! :slightly_smiling_face:

**Comment by trumpets** [comment]
Dhurim, please read my emails more carefully. It has to do with the server
change of course and it has to do with the preview images task.

If you looked at the code at all, the server for practical 2 was returning
new meal server id and the code uses that to control which meals were
updated.

That endpoint changed today and I told you that you guys need to handle the
change.
